<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-15T14:20:27+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyASo9-GUDN9rrZTFY5FdY1i_FlcL5doLKo',
        ],
    ],
];
